format_version: 10
environments:
  astrojs-highscore-site:
    environment_variables:
      AWS_ACCESS_KEY_ID: "{{SECRET:[credentials][AWS_ACCESS_KEY_ID]}}"
      AWS_SECRET_ACCESS_KEY: "{{SECRET:[credentials][AWS_SECRET_ACCESS_KEY]}}"
    pipelines:
      - deploy_highscore_site
pipelines:
  deploy_highscore_site:
    group: default
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-dbbfd34:
        git: https://github.com/gaurdianaq/astrojs-highscore-website
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - build:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: true
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            install-build:
              timeout: 0
              artifacts:
                - build:
                    source: dist
                    destination: astrojs-highscore
              tasks:
                - exec:
                    arguments:
                      - install
                    command: npm
                    working_directory: ./
                    run_if: passed
                - exec:
                    arguments:
                      - run
                      - build
                    command: npm
                    working_directory: ./
                    run_if: passed
      - packer:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            build:
              timeout: 0
              tasks:
                - fetch:
                    is_file: false
                    source: astrojs-highscore
                    destination: ./
                    pipeline: deploy_highscore_site
                    stage: build
                    job: install-build
                    artifact_origin: gocd
                    run_if: passed
                - exec:
                    arguments:
                      - init
                      - .
                    command: packer
                    working_directory: ./packer
                    run_if: passed
                - exec:
                    arguments:
                      - build
                      - -var
                      - build_location=../astrojs-highscore/dist
                      - .
                    command: packer
                    working_directory: ./packer
                    run_if: passed
      - deploy:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: true
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            terraform:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - init
                    command: terraform
                    working_directory: ./terraform
                    run_if: passed
                - exec:
                    arguments:
                      - apply
                      - -auto-approve
                      - -var
                      - ssh_key=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINgffnBNnhr/S5hhyCzS5gH6eOigMNwlQRdi/Ps7GGB/
                        evan.tatayhinds@protonmail.com
                    command: terraform
                    working_directory: ./terraform
                    run_if: passed
